name = "docker-offline-builder"
main = "src/worker.js"
compatibility_date = "2026-08-17"

[vars]
GITHUB_WORKFLOW_FILE = "build.yml"
GITHUB_OWNER = "cyz-domo"
GITHUB_REPO = "docker-offline"
GITHUB_REF = "main"
MAX_QUEUE_SIZE = "3"
MAX_REQUESTS_PER_HOUR = "10"
MAX_REQUESTS_PER_DAY = "50"
TURNSTILE_SITE_KEY = "0x4AAAAAAEShIeyc3zcZfKzf"
TURNSTILE_HOSTNAMES = "docker-offline-builder.gcst4tqsdm.workers.dev"

[[durable_objects.bindings]]
name = "BUILD_QUEUE"
class_name = "BuildQueue"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BuildQueue"]

[triggers]
crons = ["17 3 * * *"]
